# Generated by Django 6.0.5 on 2026-09-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=20)),
                ('quantidadeVagas', models.IntegerField()),
                ('vagasLivres', models.IntegerField(blank=True)),
                ('dataCadastro_quarto', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Quarto ativo')),
            ],
        ),
    ]
