# Generated by Django 6.0.5 on 2026-08-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
