# Generated by Django 6.0.5 on 2026-05-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='identificacao',
            field=models.CharField(max_length=20),
        ),
    ]
