# Generated by Django 4.2.29 on 2026-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='numero',
        ),
        migrations.AddField(
            model_name='quarto',
            name='identificacao',
            field=models.CharField(default='semid', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quarto',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Quarto ativo'),
        ),
    ]
