# Generated by Django 4.2.29 on 2026-04-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0002_remove_quarto_numero_quarto_identificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='quantidadeVagas',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarto',
            name='vagasLivres',
            field=models.IntegerField(blank=True, default='2'),
            preserve_default=False,
        ),
    ]
