# Generated by Django 6.0.5 on 2026-09-12 06:20

import django.db.models.deletion
import domain.pessoa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=30)),
                ('cpf_pessoa', models.CharField(max_length=11, unique=True)),
                ('sexo_pessoa', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('dataNasc_pessoa', models.DateField()),
                ('nacionalidade_pessoa', models.CharField(default='Brasil', max_length=20)),
                ('telefone_pessoa', models.CharField(max_length=11, unique=True)),
                ('email_pessoa', models.EmailField(blank=True, max_length=80, null=True, unique=True)),
                ('dataCadastro', models.DateField()),
                ('descricao_pessoa', models.CharField(blank=True, max_length=50)),
                ('cartao_sus', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('deficiencia', models.BooleanField(default=False, max_length=10)),
                ('tipo_deficiencia', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='FotoPerfilPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=domain.pessoa.models.caminho_upload)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_perfil', to='pessoa.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaEditada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEdicao', models.DateTimeField()),
                ('camposAlterados', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edicao', to='pessoa.pessoa')),
            ],
        ),
    ]
