# Generated by Django 4.2.29 on 2026-04-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PapelSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=30)),
                ('cpf_pessoa', models.CharField(max_length=11, unique=True)),
                ('dataNasc_pessoa', models.DateField()),
                ('telefone_pessoa', models.CharField(max_length=11)),
                ('email_pessoa', models.EmailField(max_length=80, unique=True)),
                ('aptaSolicitante_pessoa', models.BooleanField(default=False)),
                ('dataCadastro', models.DateField(auto_now_add=True)),
                ('papelSolicitante_pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pessoa.papelsolicitante')),
            ],
        ),
    ]
