# Generated by Django 4.2.29 on 2026-05-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_pessoa_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaEditada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEdicao', models.DateTimeField(auto_now_add=True)),
                ('camposAlterados', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='aptaSolicitante_pessoa',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='papelSolicitante_pessoa',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='idade_pessoa',
            field=models.IntegerField(default=2, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nacionalidade_pessoa',
            field=models.CharField(choices=[('BR', 'Brasil'), ('PY', 'Paraguai')], default='BR', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo_pessoa',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=4, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PapelSolicitante',
        ),
        migrations.AddField(
            model_name='pessoaeditada',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edicao', to='pessoa.pessoa'),
        ),
    ]
