# Generated by Django 6.0.5 on 2026-09-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_alter_pessoa_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='outra_deficiencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
