# Generated by Django 6.0.5 on 2026-09-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_pessoa_outra_deficiencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='outra_deficiencia',
        ),
    ]
