# Generated by Django 4.2.29 on 2026-05-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_pessoaeditada_remove_pessoa_aptasolicitante_pessoa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='idade_pessoa',
        ),
    ]
