# Generated by Django 6.0.5 on 2026-09-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_remove_pessoa_outra_deficiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='deficiencia',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeficienciaPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outras', models.CharField(blank=True, max_length=100, null=True)),
                ('deficiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deficiencia_deficienciaPessoa', to='pessoa.deficiencia')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_deficienciaPessoa', to='pessoa.pessoa')),
            ],
        ),
    ]
