# Generated by Django 4.2.29 on 2026-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_remove_pessoa_idade_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='descricao_pessoa',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
