# Generated by Django 6.0.5 on 2026-09-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_deficiencia_alter_pessoa_deficiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='tipo_deficiencia',
        ),
    ]
