# Generated by Django 6.0.5 on 2026-05-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_pessoa_descricao_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='novosDados',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
