# Generated by Django 6.0.5 on 2026-05-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_pessoa_novosdados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='novosDados',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dataCadastro',
            field=models.DateField(),
        ),
    ]
