# Generated by Django 6.0.5 on 2026-09-29 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_remove_pessoa_tipo_deficiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deficienciapessoa',
            name='deficiencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deficiencia_deficienciaPessoa', to='pessoa.deficiencia'),
        ),
    ]
