# Generated by Django 6.0.5 on 2026-09-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_alter_deficienciapessoa_deficiencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deficienciapessoa',
            name='outras',
        ),
    ]
