# Generated by Django 6.0.5 on 2026-05-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_remove_pessoa_novosdados_alter_pessoa_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaeditada',
            name='dataEdicao',
            field=models.DateTimeField(),
        ),
    ]
