# Generated by Django 6.0.5 on 2026-05-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_alter_pessoaeditada_dataedicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email_pessoa',
            field=models.EmailField(max_length=80),
        ),
    ]
