# Generated by Django 6.0.5 on 2026-06-21 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_endereco_descricao_endereco_pais_and_more'),
        ('pessoa', '0009_alter_pessoa_email_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco'),
        ),
    ]
