# Generated by Django 6.0.5 on 2026-06-22 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_endereco_descricao_endereco_pais_and_more'),
        ('pessoa', '0010_pessoa_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco'),
        ),
    ]
