# Generated by Django 6.0.5 on 2026-08-12 06:17

import django.db.models.deletion
import domain.pessoa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0011_alter_pessoa_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPerfilPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=domain.pessoa.models.caminho_upload)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_perfil', to='pessoa.pessoa')),
            ],
        ),
    ]
