# Generated by Django 4.2.29 on 2026-04-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasaDeApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_casaApoio', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quarto', models.IntegerField(max_length=3, unique=True)),
                ('bloco_quarto', models.CharField(max_length=2)),
                ('andar_quarto', models.CharField(max_length=2)),
                ('capacidadePacientes_quarto', models.IntegerField(max_length=2)),
                ('descricao_quarto', models.CharField(max_length=50)),
            ],
        ),
    ]
