# Generated by Django 6.0.5 on 2026-06-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='endereco',
            name='pais',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=2),
        ),
    ]
