# Generated by Django 6.0.5 on 2026-08-14 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoSolicitantePessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitantePessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=20)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacao.funcaosolicitantepessoa')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pessoa.pessoa')),
            ],
        ),
    ]
