# Generated by Django 4.2.29 on 2026-05-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0003_pessoaeditada_remove_pessoa_aptasolicitante_pessoa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoSolicitantePessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitantePessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=20)),
                ('funcao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='solicitacao.funcaosolicitantepessoa')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa')),
            ],
        ),
    ]
