# Generated by Django 6.0.5 on 2026-05-26 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_alter_pessoaeditada_dataedicao'),
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaosolicitantepessoa',
            name='descricao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='funcaosolicitantepessoa',
            name='funcao',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitantepessoa',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pessoa.pessoa'),
        ),
    ]
