# Generated by Django 6.0.5 on 2026-06-22 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_alter_funcaosolicitantepessoa_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitantepessoa',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacao.funcaosolicitantepessoa'),
        ),
    ]
