# Generated by Django 6.0.5 on 2026-09-12 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco_unidade', to='endereco.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='SetorUnidadeSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=50)),
                ('unidade_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade_setor', to='solicitante.unidadesolicitante')),
            ],
        ),
    ]
