# Generated by Django 6.0.5 on 2026-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='oidc_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
