"""
Django settings for projetoApoio project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*-pf^13iz8qwpz2uac7zck$lr6pk-3*j(szrb+!ptdv-l7#@3s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOGIN_URL = "autenticacao:login"
LOGIN_REDIRECT_URL = "home"

ALLOWED_HOSTS = ['casadeapoio.local',
                 'localhost',
                 '127.0.0.1',
                 'auth.local']

#descomente e adicione a url
#CSRF_TRUSTED_ORIGINS = [
#    "url",
#]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mozilla_django_oidc', #APP para usar OIDC
    'domain.apoio',
    'domain.pessoa',
    'domain.casadeapoio',
    'domain.quarto',
    'domain.endereco',
    'domain.solicitacao',
    'autenticacao'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projetoApoio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR /'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projetoApoio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# no postgres:  psql -U postgres -d : CREATE DATABASE casa_apoio;

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'casa_apoio',
#        'USER': 'postgres',
#        'PASSWORD': 'senha',
#        'HOST': 'postgres',
#       'PORT': '5432',
#    }
#}

#ntegração com redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'autenticacao.Usuario'

###########
#OIDC AUTH#
###########
load_dotenv(BASE_DIR/".env")

TIPO_AUTENTICACAO = os.getenv(
    "TIPO_AUTENTICACAO",
    "LOCAL"
)
if TIPO_AUTENTICACAO == "OIDC":
    AUTHENTICATION_BACKENDS = ("autenticacao.backends.AuthentikBackend",)
    OIDC_RP_CLIENT_ID = os.getenv("OIDC_CLIENT_ID")
    OIDC_RP_CLIENT_SECRET = os.getenv("OIDC_CLIENT_SECRET")
    OIDC_RP_SIGN_ALGO = "RS256"
    #OIDC_OP_DISCOVERY_ENDPOINT = (f"{os.getenv('OIDC_ISSUER')}.well-known/openid-configuration")
    OIDC_OP_AUTHORIZATION_ENDPOINT = os.getenv("OIDC_OP_AUTHORIZATION_ENDPOINT")
    OIDC_OP_TOKEN_ENDPOINT = os.getenv("OIDC_OP_TOKEN_ENDPOINT")
    OIDC_OP_USER_ENDPOINT = os.getenv("OIDC_OP_USER_ENDPOINT")
    OIDC_OP_JWKS_ENDPOINT = os.getenv("OIDC_OP_JWKS_ENDPOINT")
    OIDC_RP_SCOPES = "openid profile email"
    OIDC_OP_ISSUER = os.getenv("OIDC_ISSUER")
    OIDC_LOGIN_URL = os.getenv("OIDC_LOGIN_URL")

if TIPO_AUTENTICACAO == "LOCAL":
    AUTHENTICATION_BACKENDS = (
        "django.contrib.auth.backends.ModelBackend",
    )
###########
#OIDC AUTH#
###########

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

#TIME_ZONE = 'UTC'
TIME_ZONE = "America/Cuiaba"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]