# Generated by Django 6.0.5 on 2026-08-14 01:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
        ('quarto', '0001_initial'),
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(choices=[('PAI_MAE', 'Pai ou Mãe'), ('CONJUGUE', 'Conjugue'), ('OUTROS', 'Outros')], max_length=10)),
                ('descricaoVinculo', models.CharField(blank=True, max_length=50)),
                ('checkIn', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkOut', models.DateTimeField(blank=True, null=True)),
                ('nomeAcompanhante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_acompanhantes', to='pessoa.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoAcompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('PDF', 'Pdf'), ('FOTO', 'Foto')], default='Pdf', max_length=10)),
                ('arquivo', models.FileField(upload_to='arquivos/autorazacoes_acompanhante')),
                ('dataUpload', models.DateTimeField(auto_now_add=True)),
                ('dataAlteracao', models.DateTimeField(auto_now=True)),
                ('acompanhante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='apoio.acompanhante')),
            ],
        ),
        migrations.CreateModel(
            name='Apoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=500)),
                ('dataInicio', models.DateField()),
                ('previsaoFim_tipo', models.CharField(choices=[('HOJE', 'Hoje'), ('DATA', 'Data'), ('INDETERMINADO', 'Indeterminado')], default='HOJE', max_length=50)),
                ('previsaoFim', models.DateField(blank=True, null=True)),
                ('checkIn', models.DateTimeField(blank=True, null=True)),
                ('checkOut', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Status do Apoio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='pessoa.pessoa')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitantes', to='solicitacao.solicitantepessoa')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('PDF', 'Pdf'), ('FOTO', 'Foto')], default='Pdf', max_length=10)),
                ('arquivo', models.FileField(upload_to='arquivos/apoios')),
                ('dataUpload', models.DateTimeField(auto_now_add=True)),
                ('dataAlteracao', models.DateTimeField(auto_now=True)),
                ('apoio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='apoio.apoio')),
            ],
        ),
        migrations.AddField(
            model_name='acompanhante',
            name='apoio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhantes', to='apoio.apoio'),
        ),
        migrations.CreateModel(
            name='HistoricoPacienteApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=30)),
                ('cpf_pessoa', models.CharField(max_length=11)),
                ('inicio_apoio', models.DateField()),
                ('checkIn_paciente', models.DateTimeField()),
                ('encerramento_apoio', models.DateTimeField()),
                ('pais', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('apoio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historico_apoio', to='apoio.apoio')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_pessoa', to='pessoa.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=500, null=True)),
                ('apoio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem', to='apoio.apoio')),
            ],
        ),
        migrations.CreateModel(
            name='AlocacaoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioLocacao', models.DateField()),
                ('fimLocacao', models.DateField(blank=True, null=True)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarto_alocacao', to='quarto.quarto')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem_alocacao', to='apoio.hospedagem')),
            ],
        ),
    ]
