# Generated by Django 4.2.29 on 2026-04-11 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(choices=[('PAI_MAE', 'Pai ou Mãe'), ('CONJUGUE', 'Conjugue'), ('OUTROS', 'Outros')], max_length=10)),
                ('decricaoVinculo', models.CharField(blank=True, max_length=50)),
                ('checkIn', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkOut', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=500)),
                ('dataIncio', models.DateField()),
                ('previsaoFim_tipo', models.CharField(choices=[('HOJE', 'Hoje'), ('DATA', 'Data'), ('INDETERMINADO', 'Indeterminado')], max_length=50)),
                ('previsaoFim', models.DateField(blank=True, null=True)),
                ('checkIn', models.DateTimeField(blank=True, null=True)),
                ('checkOut', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Status do Apoio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='pessoa.pessoa')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitantes', to='pessoa.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('PDF', 'Pdf'), ('FOTO', 'Foto')], default='Pdf', max_length=10)),
                ('arquivo', models.FileField(upload_to='arquivos/apoios')),
                ('dataUpload', models.DateTimeField(auto_now_add=True)),
                ('dataAlteracao', models.DateTimeField(auto_now=True)),
                ('apoio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='apoio.apoio')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoAcompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('PDF', 'Pdf'), ('FOTO', 'Foto')], default='Pdf', max_length=10)),
                ('arquivo', models.FileField(upload_to='arquivos/autorazacoes_acompanhante')),
                ('dataUpload', models.DateTimeField(auto_now_add=True)),
                ('dataAlteracao', models.DateTimeField(auto_now=True)),
                ('acompanhante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='apoio.acompanhante')),
            ],
        ),
        migrations.AddField(
            model_name='acompanhante',
            name='apoio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhantes', to='apoio.apoio'),
        ),
        migrations.AddField(
            model_name='acompanhante',
            name='nomeAcompanhante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_acompanhantes', to='pessoa.pessoa'),
        ),
    ]
