# Generated by Django 6.0.5 on 2026-05-26 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0001_initial'),
        ('quarto', '0001_initial'),
        ('solicitacao', '0002_alter_funcaosolicitantepessoa_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acompanhante',
            old_name='decricaoVinculo',
            new_name='descricaoVinculo',
        ),
        migrations.RenameField(
            model_name='apoio',
            old_name='dataIncio',
            new_name='dataInicio',
        ),
        migrations.AlterField(
            model_name='apoio',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitantes', to='solicitacao.solicitantepessoa'),
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=500, null=True)),
                ('apoio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem', to='apoio.apoio')),
            ],
        ),
        migrations.CreateModel(
            name='AlocacaoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioLocacao', models.DateField()),
                ('fimLocacao', models.DateField(blank=True, null=True)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarto_alocacao', to='quarto.quarto')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem_alocacao', to='apoio.hospedagem')),
            ],
        ),
    ]
