# Generated by Django 6.0.5 on 2026-09-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoio',
            name='previsaoFim_tipo',
            field=models.CharField(choices=[('INTRADIA', 'Intradia'), ('DATA', 'Data'), ('INDETERMINADO', 'Indeterminado')], default='INTRADIA', max_length=50),
        ),
    ]
