# Generated by Django 6.0.5 on 2026-08-16 16:04

import django.db.models.deletion
import domain.apoio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexoapoio',
            name='dataAlteracao',
        ),
        migrations.RemoveField(
            model_name='anexoapoio',
            name='dataUpload',
        ),
        migrations.RemoveField(
            model_name='anexoapoio',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='anexoapoio',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='anexoapoio',
            name='apoio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoio_anexo', to='apoio.apoio'),
        ),
        migrations.AlterField(
            model_name='anexoapoio',
            name='arquivo',
            field=models.FileField(upload_to=domain.apoio.models.caminho_upload),
        ),
    ]
