# Generated by Django 4.2.29 on 2026-04-12 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apoio',
            old_name='dataIncio',
            new_name='dataInicio',
        ),
    ]
