# Generated by Django 6.0.5 on 2026-06-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0002_rename_decricaovinculo_acompanhante_descricaovinculo_and_more'),
        ('pessoa', '0011_alter_pessoa_endereco'),
        ('solicitacao', '0002_alter_funcaosolicitantepessoa_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoio',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='pessoa.pessoa'),
        ),
        migrations.AlterField(
            model_name='apoio',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitantes', to='solicitacao.solicitantepessoa'),
        ),
        migrations.CreateModel(
            name='HistoricoPacienteApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=30)),
                ('cpf_pessoa', models.CharField(max_length=11)),
                ('inicio_apoio', models.DateField()),
                ('checkIn_paciente', models.DateTimeField()),
                ('encerramento_apoio', models.DateTimeField()),
                ('pais', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('apoio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historico_apoio', to='apoio.apoio')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_pessoa', to='pessoa.pessoa')),
            ],
        ),
    ]
