# Generated by Django 6.0.5 on 2026-09-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0002_alter_apoio_previsaofim_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoio',
            name='dataHora_tratamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apoio',
            name='local_tratamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apoio',
            name='tratamento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
