# Generated by Django 4.2.29 on 2026-04-12 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0002_rename_dataincio_apoio_datainicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acompanhante',
            old_name='decricaoVinculo',
            new_name='descricaoVinculo',
        ),
    ]
