# Generated by Django 6.0.5 on 2026-08-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0002_remove_anexoapoio_dataalteracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexoapoio',
            name='nome_arquivo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
