# Generated by Django 6.0.5 on 2026-09-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0003_apoio_datahora_tratamento_apoio_local_tratamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoio',
            name='contato_descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apoio',
            name='contato_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apoio',
            name='contato_telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
