# Generated by Django 6.0.5 on 2026-08-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0003_alter_apoio_paciente_alter_apoio_solicitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoio',
            name='previsaoFim_tipo',
            field=models.CharField(choices=[('HOJE', 'Hoje'), ('DATA', 'Data'), ('INDETERMINADO', 'Indeterminado')], default='HOJE', max_length=50),
        ),
    ]
