# Generated by Django 4.2.29 on 2026-04-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0003_quarto_quantidadevagas_quarto_vagaslivres'),
        ('apoio', '0003_rename_decricaovinculo_acompanhante_descricaovinculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=500, null=True)),
                ('apoio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagens', to='apoio.apoio')),
            ],
        ),
        migrations.CreateModel(
            name='AlocacaoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioLocacao', models.DateField()),
                ('fimLocacao', models.DateField()),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospedagem_alocacao', to='apoio.hospedagem')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarto_alocacao', to='quarto.quarto')),
            ],
        ),
    ]
