# Generated by Django 4.2.29 on 2026-04-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0004_hospedagem_alocacaoquarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacaoquarto',
            name='fimLocacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
