# Generated by Django 4.2.29 on 2026-04-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0005_alter_alocacaoquarto_fimlocacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagem',
            name='apoio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem', to='apoio.apoio'),
        ),
    ]
