# Generated by Django 4.2.29 on 2026-05-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0006_alter_hospedagem_apoio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacaoquarto',
            name='hospedagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedagem_alocacao', to='apoio.hospedagem'),
        ),
    ]
